/**
 * Auto-generated version type mappings.
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-version-types.ts
 *
 * @module plan.generated
 */

import type { DeploymentPlan as DeploymentPlan_v3_24_0 } from '../schemas/plan/v3.24.0/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_35_0 } from '../schemas/plan/v3.35.0/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_38_0 } from '../schemas/plan/v3.38.0/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_40_1 } from '../schemas/plan/v3.40.1/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_43_0 } from '../schemas/plan/v3.43.0/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_95_0 } from '../schemas/plan/v3.95.0/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_132_0 } from '../schemas/plan/v3.132.0/plan.js'
import type { DeploymentPlan as DeploymentPlan_v3_200_0 } from '../schemas/plan/v3.200.0/plan.js'

// Re-export all plan types
export type { DeploymentPlan_v3_24_0 }
export type { DeploymentPlan_v3_35_0 }
export type { DeploymentPlan_v3_38_0 }
export type { DeploymentPlan_v3_40_1 }
export type { DeploymentPlan_v3_43_0 }
export type { DeploymentPlan_v3_95_0 }
export type { DeploymentPlan_v3_132_0 }
export type { DeploymentPlan_v3_200_0 }

// Export the latest version as DeploymentPlan
export type { DeploymentPlan_v3_200_0 as DeploymentPlan }

type PatchVersionMap_3_24 = {
  0: DeploymentPlan_v3_24_0
  MAX: DeploymentPlan_v3_24_0
}

type PatchVersionMap_3_35 = {
  0: DeploymentPlan_v3_35_0
  MAX: DeploymentPlan_v3_35_0
}

type PatchVersionMap_3_38 = {
  0: DeploymentPlan_v3_38_0
  MAX: DeploymentPlan_v3_38_0
}

type PatchVersionMap_3_40 = {
  0: DeploymentPlan_v3_38_0
  1: DeploymentPlan_v3_40_1
  MAX: DeploymentPlan_v3_40_1
}

type PatchVersionMap_3_43 = {
  0: DeploymentPlan_v3_43_0
  MAX: DeploymentPlan_v3_43_0
}

type PatchVersionMap_3_95 = {
  0: DeploymentPlan_v3_95_0
  MAX: DeploymentPlan_v3_95_0
}

type PatchVersionMap_3_132 = {
  0: DeploymentPlan_v3_132_0
  MAX: DeploymentPlan_v3_132_0
}

type PatchVersionMap_3_200 = {
  0: DeploymentPlan_v3_200_0
  MAX: DeploymentPlan_v3_200_0
}

type MinorVersionMap_3 = {
  0: never
  1: never
  2: never
  3: never
  4: never
  5: never
  6: never
  7: never
  8: never
  9: never
  10: never
  11: never
  12: never
  13: never
  14: never
  15: never
  16: never
  17: never
  18: never
  19: never
  20: never
  21: never
  22: never
  23: never
  24: PatchVersionMap_3_24
  25: PatchVersionMap_3_24
  26: PatchVersionMap_3_24
  27: PatchVersionMap_3_24
  28: PatchVersionMap_3_24
  29: PatchVersionMap_3_24
  30: PatchVersionMap_3_24
  31: PatchVersionMap_3_24
  32: PatchVersionMap_3_24
  33: PatchVersionMap_3_24
  34: PatchVersionMap_3_24
  35: PatchVersionMap_3_35
  36: PatchVersionMap_3_35
  37: PatchVersionMap_3_35
  38: PatchVersionMap_3_38
  39: PatchVersionMap_3_38
  40: PatchVersionMap_3_40
  41: PatchVersionMap_3_40
  42: PatchVersionMap_3_40
  43: PatchVersionMap_3_43
  44: PatchVersionMap_3_43
  45: PatchVersionMap_3_43
  46: PatchVersionMap_3_43
  47: PatchVersionMap_3_43
  48: PatchVersionMap_3_43
  49: PatchVersionMap_3_43
  50: PatchVersionMap_3_43
  51: PatchVersionMap_3_43
  52: PatchVersionMap_3_43
  53: PatchVersionMap_3_43
  54: PatchVersionMap_3_43
  55: PatchVersionMap_3_43
  56: PatchVersionMap_3_43
  57: PatchVersionMap_3_43
  58: PatchVersionMap_3_43
  59: PatchVersionMap_3_43
  60: PatchVersionMap_3_43
  61: PatchVersionMap_3_43
  62: PatchVersionMap_3_43
  63: PatchVersionMap_3_43
  64: PatchVersionMap_3_43
  65: PatchVersionMap_3_43
  66: PatchVersionMap_3_43
  67: PatchVersionMap_3_43
  68: PatchVersionMap_3_43
  69: PatchVersionMap_3_43
  70: PatchVersionMap_3_43
  71: PatchVersionMap_3_43
  72: PatchVersionMap_3_43
  73: PatchVersionMap_3_43
  74: PatchVersionMap_3_43
  75: PatchVersionMap_3_43
  76: PatchVersionMap_3_43
  77: PatchVersionMap_3_43
  78: PatchVersionMap_3_43
  79: PatchVersionMap_3_43
  80: PatchVersionMap_3_43
  81: PatchVersionMap_3_43
  82: PatchVersionMap_3_43
  83: PatchVersionMap_3_43
  84: PatchVersionMap_3_43
  85: PatchVersionMap_3_43
  86: PatchVersionMap_3_43
  87: PatchVersionMap_3_43
  88: PatchVersionMap_3_43
  89: PatchVersionMap_3_43
  90: PatchVersionMap_3_43
  91: PatchVersionMap_3_43
  92: PatchVersionMap_3_43
  93: PatchVersionMap_3_43
  94: PatchVersionMap_3_43
  95: PatchVersionMap_3_95
  96: PatchVersionMap_3_95
  97: PatchVersionMap_3_95
  98: PatchVersionMap_3_95
  99: PatchVersionMap_3_95
  100: PatchVersionMap_3_95
  101: PatchVersionMap_3_95
  102: PatchVersionMap_3_95
  103: PatchVersionMap_3_95
  104: PatchVersionMap_3_95
  105: PatchVersionMap_3_95
  106: PatchVersionMap_3_95
  107: PatchVersionMap_3_95
  108: PatchVersionMap_3_95
  109: PatchVersionMap_3_95
  110: PatchVersionMap_3_95
  111: PatchVersionMap_3_95
  112: PatchVersionMap_3_95
  113: PatchVersionMap_3_95
  114: PatchVersionMap_3_95
  115: PatchVersionMap_3_95
  116: PatchVersionMap_3_95
  117: PatchVersionMap_3_95
  118: PatchVersionMap_3_95
  119: PatchVersionMap_3_95
  120: PatchVersionMap_3_95
  121: PatchVersionMap_3_95
  122: PatchVersionMap_3_95
  123: PatchVersionMap_3_95
  124: PatchVersionMap_3_95
  125: PatchVersionMap_3_95
  126: PatchVersionMap_3_95
  127: PatchVersionMap_3_95
  128: PatchVersionMap_3_95
  129: PatchVersionMap_3_95
  130: PatchVersionMap_3_95
  131: PatchVersionMap_3_95
  132: PatchVersionMap_3_132
  133: PatchVersionMap_3_132
  134: PatchVersionMap_3_132
  135: PatchVersionMap_3_132
  136: PatchVersionMap_3_132
  137: PatchVersionMap_3_132
  138: PatchVersionMap_3_132
  139: PatchVersionMap_3_132
  140: PatchVersionMap_3_132
  141: PatchVersionMap_3_132
  142: PatchVersionMap_3_132
  143: PatchVersionMap_3_132
  144: PatchVersionMap_3_132
  145: PatchVersionMap_3_132
  146: PatchVersionMap_3_132
  147: PatchVersionMap_3_132
  148: PatchVersionMap_3_132
  149: PatchVersionMap_3_132
  150: PatchVersionMap_3_132
  151: PatchVersionMap_3_132
  152: PatchVersionMap_3_132
  153: PatchVersionMap_3_132
  154: PatchVersionMap_3_132
  155: PatchVersionMap_3_132
  156: PatchVersionMap_3_132
  157: PatchVersionMap_3_132
  158: PatchVersionMap_3_132
  159: PatchVersionMap_3_132
  160: PatchVersionMap_3_132
  161: PatchVersionMap_3_132
  162: PatchVersionMap_3_132
  163: PatchVersionMap_3_132
  164: PatchVersionMap_3_132
  165: PatchVersionMap_3_132
  166: PatchVersionMap_3_132
  167: PatchVersionMap_3_132
  168: PatchVersionMap_3_132
  169: PatchVersionMap_3_132
  170: PatchVersionMap_3_132
  171: PatchVersionMap_3_132
  172: PatchVersionMap_3_132
  173: PatchVersionMap_3_132
  174: PatchVersionMap_3_132
  175: PatchVersionMap_3_132
  176: PatchVersionMap_3_132
  177: PatchVersionMap_3_132
  178: PatchVersionMap_3_132
  179: PatchVersionMap_3_132
  180: PatchVersionMap_3_132
  181: PatchVersionMap_3_132
  182: PatchVersionMap_3_132
  183: PatchVersionMap_3_132
  184: PatchVersionMap_3_132
  185: PatchVersionMap_3_132
  186: PatchVersionMap_3_132
  187: PatchVersionMap_3_132
  188: PatchVersionMap_3_132
  189: PatchVersionMap_3_132
  190: PatchVersionMap_3_132
  191: PatchVersionMap_3_132
  192: PatchVersionMap_3_132
  193: PatchVersionMap_3_132
  194: PatchVersionMap_3_132
  195: PatchVersionMap_3_132
  196: PatchVersionMap_3_132
  197: PatchVersionMap_3_132
  198: PatchVersionMap_3_132
  199: PatchVersionMap_3_132
  200: PatchVersionMap_3_200
  MAX: PatchVersionMap_3_200
}

type MajorVersionMap = {
  0: never
  1: never
  2: never
  3: MinorVersionMap_3
  MAX: MinorVersionMap_3
}

/**
 * Helper type to get the max (last) value from a map when accessing by index.
 * If the key exists, returns the value at that key.
 * Otherwise, returns the value at the 'MAX' key (the max version).
 */
type GetFromMapOrMax<Map extends { MAX: unknown }, Key> = 
  Key extends keyof Map 
    ? Map[Key]
    : Map['MAX']

/**
 * Internal type to look up plan type from version components.
 */
type LookupPlanType<Major extends number, Minor extends number, Patch extends number> =
  Major extends keyof MajorVersionMap
    ? MajorVersionMap[Major] extends infer MinorMap
      ? [MinorMap] extends [never]
        ? never
        : MinorMap extends { MAX: unknown }
          ? Minor extends keyof MinorMap
            ? MinorMap[Minor] extends infer PatchMap
              ? [PatchMap] extends [never]
                ? never
                : PatchMap extends { MAX: unknown }
                  ? GetFromMapOrMax<PatchMap, Patch>
                  : never
              : never
            : GetFromMapOrMax<MinorMap, Minor> extends infer PatchMap
              ? [PatchMap] extends [never]
                ? never
                : PatchMap extends { MAX: unknown }
                  ? GetFromMapOrMax<PatchMap, Patch>
                  : never
              : never
          : never
      : never
    : DeploymentPlan_v3_200_0

/**
 * Extract version components and look up the corresponding plan type.
 * Returns 'never' for versions before v3.24.0.
 * Returns the maximum matching version type for versions beyond our known schemas.
 */
export type DeploymentPlanForVersion<V extends string> =
  V extends `v${infer Major extends number}.${infer Minor extends number}.${infer Patch extends number}`
    ? LookupPlanType<Major, Minor, Patch>
    : V extends `v${infer Major extends number}.${infer Minor extends number}.${infer Patch extends number}-${string}`
    ? LookupPlanType<Major, Minor, Patch>
    : V extends `v${infer Major extends number}.${infer Minor extends number}.${infer Patch extends number}+${string}`
    ? LookupPlanType<Major, Minor, Patch>
    : V extends `${infer Major extends number}.${infer Minor extends number}.${infer Patch extends number}`
    ? LookupPlanType<Major, Minor, Patch>
    : V extends `${infer Major extends number}.${infer Minor extends number}.${infer Patch extends number}-${string}`
    ? LookupPlanType<Major, Minor, Patch>
    : V extends `${infer Major extends number}.${infer Minor extends number}.${infer Patch extends number}+${string}`
    ? LookupPlanType<Major, Minor, Patch>
    : never

/**
 * Union type of all available schema versions.
 */
export type Version = 'v3.24.0' | 'v3.35.0' | 'v3.38.0' | 'v3.40.1' | 'v3.43.0' | 'v3.95.0' | 'v3.132.0' | 'v3.200.0'
